CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content    VARCHAR(255)                            NOT NULL,
    task_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_TASK FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE task
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    priority     VARCHAR(255)                            NOT NULL,
    initiator_id BIGINT,
    executor_id  BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_EXECUTOR FOREIGN KEY (executor_id) REFERENCES users (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id);

CREATE TABLE token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    access_token  VARCHAR(255)                            NOT NULL,
    refresh_token VARCHAR(255)                            NOT NULL,
    is_logged_out BOOLEAN                                 NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE users
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email                      VARCHAR(255)                            NOT NULL,
    password                   VARCHAR(255)                            NOT NULL,
    first_name                 VARCHAR(255)                            NOT NULL,
    patronymic                 VARCHAR(255)                            NOT NULL,
    last_name                  VARCHAR(255)                            NOT NULL,
    is_account_non_expired     BOOLEAN                                 NOT NULL,
    is_account_non_locked      BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    role                       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);